add mui and barebones components to project
chrispinkney/cinesync pull request #22
Opened 2023-09-20 02:28 UTC by Thinbishop

Closes #8, #16, and #20.

### Description
This PR adds [Material UI](https://mui.com/) as a dependency to the project, along with several roughed-in components and routes:

- `Header` component (#8 )
- `Sidebar` component
- `Footer` component
- `About` route
- `loading.tsx` (#20) and `not-found.tsx` app-level pages

Material UI has been implemented using `theme.ts` and `ThemeRegistry.tsx` in the `web/theme` directory, using a reference implementation from [https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs-ts](https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs-ts)
(#16) 

The mui theme is currently set to only use dark mode. Addition of light mode will be a point of discussion.

### Testing
Start the server with `npm run dev` from `./web` and test the following:

- `'/'` route is intact.
- Clicking the page header logo will navigate to `'/'`.
- Clicking the `Home` item in the sidebar will navigate to `'/'`.
- Clicking the `About` item in the sidebar will navigate to `'/about'`.
- Clicking the profile avatar in the header will open a drop down menu.
- Clicking any other links will first bring up the `loading.tsx` content, then the `not-found.tsx` content

2023-09-20 03:00 UTC, chrispinkney requested changes
This is honestly FANTASTIC work man, seriously. This is a massive PR that changes a lot, and I was not expecting this so soon.

However, this is a lot. If some of the change requested are a lot of work please feel free to break this down over several PRs instead of one big one to try and manage the work.

I added some comments based on my old Next.JS knowledge which might not apply to 13, so feel free to correct me.

2023-09-20 03:13 UTC, chrispinkney commented on web/src/app/loading.module.css
> +}
needs a newline here

2023-09-20 03:17 UTC, chrispinkney commented on web/src/app/loading.tsx
> +export default function Loading() {
I think we should use ES6+ conventions (arrow functions, etc.) instead of using old JS syntax

2023-09-20 03:17 UTC, chrispinkney commented on web/theme/ThemeRegistry.tsx
> +export default function ThemeRegistry({
see es6 comment above

2023-09-20 03:18 UTC, chrispinkney commented on web/theme/EmotionCache.tsx
> +export default function NextAppDirEmotionCacheProvider(
see es6 comment above (unless we're removing this file later)

2023-09-20 03:20 UTC, chrispinkney commented
Also I'm not sure why clicking the links reloads the entire page?

2023-09-20 22:52 UTC, Thinbishop commented on web/src/app/about/page.tsx
> +'use client';
Any component that uses React.useState() or .useEffect() will throw a runtime error stating that it requires 'use client'

2023-09-21 22:23 UTC, chrispinkney requested changes
Almost done! Eager to see what you can dig up about the emotion situation.

2023-09-21 22:23 UTC, chrispinkney commented on web/src/app/icon.ico
Can you replace the favicon.ico with this instead of deleting it? It doesn't really matter but may as well go with web conventions.

2023-09-21 22:23 UTC, chrispinkney commented on web/src/app/loading.module.css
> +	/*   animation: rotate 3s linear infinite */
Remove if not being used please and thanks 😃

2023-09-28 17:28 UTC, Thinbishop commented on web/src/app/loading.module.css
> +}
fixed

2023-09-28 17:36 UTC, Thinbishop commented on web/src/app/loading.tsx
> +export default function Loading() {
I've updated these for all but the root layout

2023-09-28 17:51 UTC, Thinbishop commented on web/src/app/loading.module.css
> +	/*   animation: rotate 3s linear infinite */
Removed commented line

2023-09-28 17:55 UTC, Thinbishop commented on web/theme/EmotionCache.tsx
> +import * as React from 'react';
Updated all files to call only what's required from react

2023-09-28 17:57 UTC, Thinbishop commented on web/public/cinesync-icon.png
We can remove these later on if we don't need them. I'll add an issue to track it.

2023-09-28 17:59 UTC, Thinbishop commented on web/src/app/loading.module.css
> +@import url(https://fonts.googleapis.com/css?family=Shadows+Into+Light);
This has been implemented

2023-09-28 18:02 UTC, Thinbishop commented on web/theme/EmotionCache.tsx
> +						// eslint-disable-next-line react/no-danger
Still not sure if there is a better way to do this with Next/mui/emotion. I'll keep an eye on it to see what we can do.

2023-09-28 18:02 UTC, Thinbishop commented on web/src/components/Header/Header.tsx
> +import React, { FunctionComponent } from 'react';
Implemented

2023-09-28 18:10 UTC, Thinbishop commented on web/src/app/icon.ico
Corrected this. It wasn't working at first, which is why I had set it to icon.ico, but after doing a hard refresh, it worked.

2023-09-28 20:01 UTC, chrispinkney approved these changes
Great work!

2023-09-28 20:01 UTC, merged