Issue 12: Implement Meta Tags
chrispinkney/cinesync pull request #80
Opened 2023-10-18 00:19 UTC by Thinbishop

## Issue

Closes #12 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Adding meta tags allows the app to display correct titles in broswer tabs and where links are shared. Since the majority of the pages require `'use client'`, this has been implemented only into the top level `layout.tsx` file. However, title templating was added in case furuter implementation allows for metadata in page paths.

## Testing the PR

See [readme](https://github.com/chrispinkney/cinesync#running-cinesync)

## Checklist

- [x] **Quality**: This PR builds and passes the respective npm run test and works locally
- [ ] **Tests**: This PR includes thorough tests
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2023-10-18 13:38 UTC, chrispinkney requested changes
@Thinbishop Can you also change it for the About page? Not sure if it's possible, when I tried it it didn't seem so.

2023-10-18 13:38 UTC, chrispinkney commented on web/src/app/layout.tsx
> +		url: 'https://cinemasync.me/',
cinesync.me

2023-10-18 18:33 UTC, Thinbishop commented
> @Thinbishop Can you also change it for the About page? Not sure if it's possible, when I tried it it didn't seem so.

It isn't possible in its current configuration because we are using client on the about page for text theming. It only works on server components that either have no client components imported or are passed client components as children.

2023-10-19 00:41 UTC, chrispinkney approved these changes

2023-10-19 00:42 UTC, merged