Issue-51: Movie form autopopulation when adding to a List
chrispinkney/cinesync pull request #89
Opened 2023-10-20 16:22 UTC by Thinbishop

## Issue

Closes #51

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Currently, movies need to be manually added and their details populated in a movie list. Integrating [TMDB](www.themoviedb.org) as a data source will allow us to populate movie details automatically.

When editing a movie list, the user can click to add a movie, then search for their movie and once found, they can select it. The movie will be automatically added to the movie list. 

This also changes the editability of the movie list `<Datagrid/>` component, and required removal of the `<GenreDropdown/>` in favour of a `<GenreDisplay/>`, in which the chips are displayed, without a dropdown selection menu.

Additionally, tool tip styling has been changed in `theme.ts` . The background color has been changed to black at 70% transparency.

lodash has been added as a dependency to implement search text debounce.

## Testing the PR

- run backend as usual
- `cd /web` -> `npm` i` to install lodash
- `npm run dev`
- Create a list and go to its page
- Click the ➕ button on the list to open the add movie dialog
- Search for and add various movies. 
  - These should be added to the list, but not saved.
  - To save, click the list save icon as usual.
- Test that the movie search details are cleared when closing the dialog.

## Checklist

- [x] **Quality**: This PR builds and passes the respective npm run test and works locally
- [ ] **Tests**: This PR includes thorough tests
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2023-10-20 17:06 UTC, chrispinkney commented on node_modules/.package-lock.json
What is this file? I don't think we need it

2023-10-20 17:18 UTC, chrispinkney requested changes
Amazing, amazing work. Truly amazing. This is my favourite thing that's been added to the app so far.

2023-10-20 17:18 UTC, chrispinkney commented on node_modules/.package-lock.json
What is this file? I don't think we need it?

2023-10-20 17:18 UTC, chrispinkney commented on node_modules/lodash.debounce/LICENSE
same

2023-10-20 17:18 UTC, chrispinkney commented on node_modules/lodash.debounce/README.md
why is node_modules even being committed? odd

2023-10-20 17:18 UTC, chrispinkney commented on node_modules/lodash.debounce/index.js
same

2023-10-20 17:18 UTC, chrispinkney commented on node_modules/lodash.debounce/package.json
same

2023-10-20 17:18 UTC, chrispinkney commented on package-lock.json
same

2023-10-20 17:18 UTC, chrispinkney commented on web/public/tmdb-primary-long.svg
For the attribution I think? Cool!

2023-10-20 17:18 UTC, chrispinkney commented on web/src/components/List/MovieCard/MovieCard.tsx
> +							<img
Does this need to be img instead of using nextjs' Image function? just asking, I have no idea

2023-10-20 17:18 UTC, chrispinkney commented on web/src/components/List/MovieCard/MovieCard.tsx
> +							<img
also eslint disables make baby jesus cry but its fine

2023-10-20 17:18 UTC, chrispinkney commented on web/src/components/List/MovieListTable/GenreDisplay.tsx
> +'use client';
does this need to be client based?

2023-10-20 17:18 UTC, chrispinkney commented on web/src/components/List/MovieListTable/MovieAddModal.tsx
> +					// height: 660,
does it need this comment?

2023-10-20 17:18 UTC, chrispinkney commented on web/src/components/List/MovieListTable/MovieListTable.tsx
> +		console.dir(movieListTableRows);
remove please 😛

2023-10-20 17:18 UTC, chrispinkney commented on web/src/utils/tmdb-api.ts
> +	console.log(searchText);
yo quiero taco bell

2023-10-20 17:18 UTC, chrispinkney commented on web/src/utils/tmdb-api.ts
> +	console.dir(movieSearchResults);
one more

2023-10-20 17:18 UTC, chrispinkney commented on web/src/utils/tmdb-api.ts
> +	console.log(movieId);
und here

2023-10-20 17:18 UTC, chrispinkney commented on web/src/utils/tmdb-api.ts
> +	console.dir(movieDetails);
c'est la vie

2023-10-20 17:43 UTC, Thinbishop commented on node_modules/.package-lock.json
fixed all dependencies

2023-10-20 17:43 UTC, Thinbishop commented on web/src/components/List/MovieListTable/GenreDisplay.tsx
> +'use client';
fixed

2023-10-20 17:43 UTC, Thinbishop commented on web/src/components/List/MovieListTable/MovieAddModal.tsx
> +					// height: 660,
removed

2023-10-20 17:44 UTC, Thinbishop commented on web/src/components/List/MovieListTable/MovieListTable.tsx
> +		console.dir(movieListTableRows);
removed all console logs

2023-10-21 17:39 UTC, chrispinkney approved these changes
Finally, perfection achieved

2023-10-21 19:58 UTC, merged