feat(web): implemented user profile page
chrispinkney/cinesync pull request #90
Opened 2023-10-20 16:23 UTC by pyvelkov

## Issue
closes #3 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Adds user settings/profile page which implements:
- updating user details (username, email, password)
- account deleting
- uploading new avatar (need to revisit with backend changes)

## Testing the PR
- cd web
- npm i
- npm run dev

## Checklist

- [ ] **Quality**: This PR builds and passes the respective npm run test and works locally
- [ ] **Tests**: This PR includes thorough tests
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2023-10-20 20:58 UTC, Thinbishop requested changes
Testing unsuccessful. After changing password, I could not log in with either new or old password. I tried this with 2 users and it was the same both times.

2023-10-20 21:36 UTC, chrispinkney requested changes
Updating password doesn't work, but I think that's my fault, looks like after adding the encryption to the db I didn't encrypt the new password so they're all stored in plaintext and the user will never be able to sign in again after changing it (see Jon's message). I'll get on a fix for that soon.

Also is update avatar supposed to be working?

Also Also, everything is kind of misaligned due to the error messages:

![image](https://github.com/chrispinkney/cinesync/assets/7242003/2da6bca5-1adf-4ac5-a555-3ee3892c5fe0)

2023-10-20 21:36 UTC, chrispinkney commented on web/public/luffy_placeholder_avatar.jpg
Do we need this?

2023-10-20 21:36 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +										? 'Username has to be more than 3 chars.'
In the code you do >= 3, so this message isn't accurate I think

2023-10-20 21:36 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +										? 'Password has to be more than 6 chars.'
In the code you do >= 6, so this message isn't accurate I think

2023-10-20 21:36 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +			userData.password.length >= 6 &&
Didn't we add zod to the frontend? Can't we use that for checking password, username, and email?

2023-10-20 21:36 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +		var re = /\S+@\S+\.\S+/;
Can we use zod for this?

2023-10-20 21:36 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +							src="/luffy_placeholder_avatar.jpg"
Can we use the initial avatar one instead?

2023-10-21 15:01 UTC, pyvelkov commented on web/public/luffy_placeholder_avatar.jpg
deleted it!

2023-10-21 15:01 UTC, pyvelkov commented on web/src/app/dashboard/userprofile/page.tsx
> +										? 'Username has to be more than 3 chars.'
This is correct. Tested.

2023-10-21 15:01 UTC, pyvelkov commented on web/src/app/dashboard/userprofile/page.tsx
> +										? 'Password has to be more than 6 chars.'
This is correct. Tested.

2023-10-21 15:55 UTC, chrispinkney commented on web/src/app/dashboard/userprofile/page.tsx
> +	}, []);
React Hook useEffect has missing dependencies: 'getAvatar' and 'getUser'. Either include them or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)

2023-10-21 15:55 UTC, chrispinkney commented on web/src/components/Header/AvatarLogo.tsx
> +	});
without a dependency array doesnt this run forever if the condition passes?

2023-10-21 22:25 UTC, Thinbishop requested changes
The only major issue I've noticed is the `/download` being called due to the missing dependency of the useEffect (see @chrispinkney's review).

A couple suggestions I would give:
- The password in the user page is showing error without any interaction, it should start without an error until the user begins typing.
- We probably would benefit from a user context, this could contain the user id, username, avatar, etc. This would allow the Header avatar to update when the context changes, then we would only need one instance each of `/download` and `/whoami`.
- The user is required to enter their password to change their username or email. I'm not sure if this is intended, because the backend has all fields optional (incl. password) during user update.
- The page.tsx file is huge. It might be beneficial to break it up into smaller components to assist with readability and future debugging/extension.

2023-10-23 18:16 UTC, chrispinkney commented
@pyvelkov Can you fix this PR to use the new util functions? (see [#106](https://github.com/chrispinkney/cinesync/pull/106/files))

2023-11-01 00:48 UTC, chrispinkney requested changes

2023-11-01 00:48 UTC, chrispinkney commented on web/src/components/UserProfile/DeleteUserProfile.tsx
> +import Grid from '@mui/material/Unstable_Grid2'; // Grid version 2
remove comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/components/UserProfile/ProfileBottom.tsx
> +import Grid from '@mui/material/Unstable_Grid2'; // Grid version 2
delete comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/components/UserProfile/ProfileTop.tsx
> +import Grid from '@mui/material/Unstable_Grid2'; // Grid version 2
delete comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/components/UserProfile/UploadAvatarImage.tsx
> +import Grid from '@mui/material/Unstable_Grid2'; // Grid version 2
delete comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/components/UserProfile/UploadAvatarImage.tsx
> +				`${process.env.NEXT_PUBLIC_URL}/auth/upload` ||
can you throw this into the new url file?

2023-11-01 00:48 UTC, chrispinkney commented on web/src/context/user.context.tsx
> +// type User = {
delete comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/context/user.context.tsx
> +		// const { success, fetchResponseJson } = await getUserAvatar({
delete comment

2023-11-01 00:48 UTC, chrispinkney commented on web/src/context/user.context.tsx
> +	// Come back to this later (used for header)
delete comment

2023-11-01 13:25 UTC, Thinbishop requested changes

2023-11-01 13:25 UTC, Thinbishop commented on web/src/components/Header/AvatarLogo.tsx
> +	// Come back to this later (see user.context)
This comment should be deleted. Maybe add as an issue?

2023-11-01 18:29 UTC, chrispinkney approved these changes

2023-11-01 18:30 UTC, merged